### ISSUE TITLE
Tutorial first popup shows on login and on logout

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Serengeti#82]
The tutorial Welcome dialog seems to be showing even when logged in or when logging out. Not sure if this is caused by my logging changes committed on Friday or if it was a pre-existing bug - will investigate on Monday.

**Comment by chrissnyder** [comment]
Pretty sure this is a result of the version of zootorial. The one specified in the fix-deps branch should fix this.

**Comment by alexbfree** [comment]
Thanks @chrissnyder . I just tested reverting the code to the version prior to my changes and confirmed that my logging changes did not break it. I will checkout the zootorial dep you mentioned.

**Comment by alexbfree** [comment]
@chrissnyder I tried the fix-dependencies branch but that makes things worse - we get a version warning in Chrome, and the rogue tutorial popup still happens. I guess this will need deeper investigation, but it might be good if whoever is expert in zootorial looks at it

**Comment by alexbfree** [comment]
Fixed - https://github.com/zooniverse/Serengeti/pull/83
